#!/usr/bin/env python3
"""Generate a single-lever A/B arm config from a base config.

Rigor tool: writes <base>__<tag>.json differing from the base by EXACTLY the
MotorEPM params given on the command line, then PRINTS the resulting diff so the
arm can never silently be something other than what was intended (CLAUDE.md §3.2
"silent confound" / "tautology" — read the running params, don't assume them).

Refuses to write an arm whose params are already at the requested value (that is a
TAUTOLOGY, not an experiment) unless --allow-noop is passed.

Usage:
  mkarm.py <base_config.json> <tag> key=value [key=value ...]
    value is parsed as JSON, so:  stance_lift_gain=0.8  gait_phase=[0,3.14159,4.71239,1.5708]
"""
import json, os, sys

CFG = "/home/xaqmusic/xaq-ai/godot_host/project/addons/ami_ogma/configs"

def main(argv):
    if len(argv) < 3:
        print(__doc__); return 2
    base, tag, kvs = argv[0], argv[1], argv[2:]
    with open(os.path.join(CFG, base)) as f:
        d = json.load(f)
    mods = [m for m in d["modules"] if m.get("type") == "MotorEPM"]
    if len(mods) != 1:
        print(f"ERROR: expected exactly 1 MotorEPM module, found {len(mods)}"); return 1
    p = mods[0]["params"]

    changes, noops = [], []
    for kv in kvs:
        k, _, raw = kv.partition("=")
        try:
            v = json.loads(raw)
        except json.JSONDecodeError:
            v = raw                      # bare string (e.g. a topic name)
        old = p.get(k, "<unset>")
        if old == v:
            noops.append(f"{k}: already {json.dumps(v)}")
        else:
            changes.append(f"{k}: {json.dumps(old)} -> {json.dumps(v)}")
        p[k] = v

    if noops and "--allow-noop" not in argv:
        print("REFUSED — these would be no-ops (tautology, not an experiment):")
        for n in noops: print("   ", n)
        print("  pass --allow-noop if that is genuinely intended")
        return 1

    stem = os.path.splitext(base)[0]
    out = f"{stem}__{tag}.json"
    # Name the arm in metadata so a UI/log line identifies which arm produced it.
    d.setdefault("metadata", {})["name"] = f"ARM {tag} (base {stem})"
    d["metadata"]["description"] = ("AUTOGENERATED A/B ARM. Single-lever delta from "
                                    f"{base}: {'; '.join(changes) or 'none'}")
    with open(os.path.join(CFG, out), "w") as f:
        json.dump(d, f, indent=1)
    print(f"wrote {out}")
    for c in changes: print("   ", c)
    return 0

if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
